# Generated by Django 2.2.7 on 2019-12-22 17:26

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_biographypage_compositionlistingpage_compositionpage_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionpage',
            name='collaborator',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Others that Decruck collaborated with.'),
        ),
        migrations.AlterField(
            model_name='compositionpage',
            name='duration',
            field=models.DurationField(blank=True, help_text='Expects data in the format "DD HH:MM:SS.uuuuuu"', null=True),
        ),
        migrations.AlterField(
            model_name='compositionpage',
            name='manuscript_status',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Notes about the location and condition of the manuscript.'),
        ),
        migrations.AlterField(
            model_name='compositionpage',
            name='orchestral_instrumentation',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='If the composition is for an ensemble, use this field to enter the orchestration of the work.'),
        ),
        migrations.AlterField(
            model_name='compositionpage',
            name='published_work_link',
            field=models.URLField(blank=True, help_text='A URL to the published score.'),
        ),
        migrations.AlterField(
            model_name='compositionpage',
            name='recording_link',
            field=models.CharField(blank=True, help_text='The You Tube id of a recording.', max_length=256),
        ),
        migrations.AlterField(
            model_name='compositionpage',
            name='text_source',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The source of the text used in the compostition.'),
        ),
    ]
