# Generated by Django 2.2.9 on 2020-01-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_compositionedtf'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionedtf',
            name='nat_lang_edtf_string',
            field=models.CharField(default='Nat lang default', help_text='Nat lang help', max_length=256, verbose_name='Natural language date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compositionedtf',
            name='edtf_string',
            field=models.CharField(max_length=256, verbose_name='EDTF Date'),
        ),
    ]
