# Generated by Django 2.2.10 on 2020-02-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200216_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionpage',
            name='published_work_link',
            field=models.URLField(blank=True, help_text='A URL to the published score.', null=True),
        ),
    ]
