# Generated by Django 2.2.10 on 2020-02-18 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200216_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionedtf',
            name='nat_lang_year',
            field=models.CharField(default='1946', editable=False, max_length=9),
            preserve_default=False,
        ),
    ]
