# Generated by Django 2.2.12 on 2020-05-22 19:37

import django.core.validators
from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200502_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scorepage',
            options={'verbose_name': 'Score Page'},
        ),
        migrations.AddField(
            model_name='scorepage',
            name='date',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='scorepage',
            name='preview_score',
            field=models.FileField(default=1, upload_to='preview_scores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scorepage',
            name='file',
            field=models.FileField(upload_to='scores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'zip'])]),
        ),
        migrations.RemoveField(
            model_name='scorepage',
            name='instrumentation',
        ),
        migrations.AddField(
            model_name='scorepage',
            name='instrumentation',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, help_text='The instrumentation of the compostition.', to='main.Instrument'),
        ),
    ]
