# Generated by Django 2.2.12 on 2020-05-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200522_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scorepage',
            name='preview_score_checksum',
        ),
    ]
