# Generated by Django 2.2.12 on 2020-05-24 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_scorepage_preview_score_checksum'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviewScoreImageProcessingLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview_score_lock', to='main.ScorePage')),
            ],
        ),
    ]
