# Generated by Django 2.2.12 on 2020-05-30 21:14

import decruck.main.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='initiator_ip',
            field=models.GenericIPAddressField(default='0.0.0.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PAYMENT_RECEIVED', 'Payment Received'), ('FILE_LINKS_SENT', 'File Links Sent')], default='INITIATED', max_length=24),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='order',
            name='paypay_ipn',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='ipn.PayPalIPN'),
        ),
        migrations.CreateModel(
            name='OrderItemLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(default=decruck.main.models.plus_one_day)),
                ('accessed', models.DateTimeField(auto_now=True)),
                ('access_ip', models.GenericIPAddressField()),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='main.OrderItem')),
            ],
        ),
    ]
