# Generated by Django 2.2.12 on 2020-05-31 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200530_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='uuid',
        ),
    ]
