# Generated by Django 2.2.12 on 2020-05-31 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200531_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paypay_ipn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='ipn.PayPalIPN'),
        ),
    ]
