# Generated by Django 3.0.8 on 2020-07-09 20:16

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200623_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('sender_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.RemoveField(
            model_name='contactformpage',
            name='confirmation_page_text',
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='message_recipients',
            field=wagtail.core.fields.StreamField([('email_address', wagtail.core.blocks.EmailBlock())], default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('PAYMENT_RECEIVED', 'Payment Received')], default='INITIATED', max_length=24),
        ),
    ]
