# Generated by Django 3.0.8 on 2020-07-17 13:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20200717_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='body_fr',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='compositionpage',
            name='description_en',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositionpage',
            name='description_fr',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compositionpage',
            name='manuscript_status_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Notes about the location and condition of the manuscript.', null=True),
        ),
        migrations.AddField(
            model_name='compositionpage',
            name='manuscript_status_fr',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Notes about the location and condition of the manuscript.', null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='contactformpage',
            name='body_fr',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='scorelistingpage',
            name='description_en',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='scorelistingpage',
            name='description_fr',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='scorepage',
            name='description_en',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='scorepage',
            name='description_fr',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='scorepage',
            name='materials_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The materials sent in the PDF file.', null=True),
        ),
        migrations.AddField(
            model_name='scorepage',
            name='materials_fr',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='The materials sent in the PDF file.', null=True),
        ),
        migrations.AddField(
            model_name='shoppingcartpage',
            name='body_en',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='shoppingcartpage',
            name='body_fr',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='shoppingcartpage',
            name='confirmation_page_text_en',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
        migrations.AddField(
            model_name='shoppingcartpage',
            name='confirmation_page_text_fr',
            field=wagtail.core.fields.StreamField([('rich_text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], null=True),
        ),
    ]
