# Generated by Django 3.0.8 on 2020-07-28 02:46

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20200717_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionpage',
            name='information_up_to_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compositionpage',
            name='premiere',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='compositionpage',
            name='scanned',
            field=models.BooleanField(default=False),
        ),
    ]
