# Generated by Django 3.0.8 on 2020-08-15 15:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200728_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='compositionpage',
            name='preview_score',
            field=models.FileField(null=True, upload_to='composition_preview_scores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='compositionpage',
            name='preview_score_checksum',
            field=models.CharField(blank=True, editable=False, max_length=256),
        ),
        migrations.CreateModel(
            name='CompositionPreviewScoreImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_score_image', models.ImageField(upload_to='composition_score_preview_images/')),
                ('page_number', models.PositiveSmallIntegerField()),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_score_images', to='main.CompositionPage')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('score', 'page_number')},
            },
        ),
    ]
