# Generated by Django 3.0.8 on 2020-08-15 17:32

from django.db import migrations

def migrate_genre_data(apps, schema_editor):
    CompositionPage = apps.get_model('main', 'CompositionPage')
    ScorePage = apps.get_model('main', 'ScorePage')

    for p in CompositionPage.objects.all():
        if p.genre:
            p.genre_temp.add(p.genre)
            p.save()

    for p in ScorePage.objects.all():
        if p.genre:
            p.genre_temp.add(p.genre)
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20200815_1731'),
    ]

    operations = [
        migrations.RunPython(migrate_genre_data)
    ]
