# Generated by Django 3.0.8 on 2020-08-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200815_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositionpage',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='scorepage',
            name='genre',
        ),
    ]
