# Generated by Django 3.0.8 on 2020-08-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200815_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compositionpage',
            old_name='genre_temp',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='scorepage',
            old_name='genre_temp',
            new_name='genre',
        ),
    ]
