# Generated by Django 3.0.8 on 2020-08-15 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200815_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionpage',
            name='preview_score',
            field=models.FileField(blank=True, null=True, upload_to='composition_preview_scores/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
