# Generated by Django 3.0.8 on 2020-08-15 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20200815_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compositionpage',
            name='published_work_link',
        ),
    ]
