# Generated by Django 3.0.8 on 2020-12-29 03:35

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_remove_compositionpage_published_work_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compositionpage',
            name='genre',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='compositions', to='main.Genre'),
        ),
        migrations.AlterField(
            model_name='scorepage',
            name='genre',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, related_name='scores', to='main.Genre'),
        ),
    ]
