# Generated by Django 3.0.11 on 2020-12-30 20:04

from django.db import migrations
from importlib import import_module

def copy_edtf(apps, schema_editor):
    """
    Copies EDTF data to its related composition
    """
    try:
        CompositionEDTF = import_module('decruck.main.models').CompositionEDTF
    except ModuleNotFoundError:
        # This model will be removed in a later migration, this exception will
        # prevent this migration from breaking future migrations
        return

    for edtf in CompositionEDTF.objects.all():
        comp = edtf.composition
        comp.nat_lang_edtf_string = edtf.nat_lang_edtf_string
        comp.edtf_string = edtf.edtf_string
        comp.lower_fuzzy = edtf.lower_fuzzy
        comp.upper_fuzzy = edtf.upper_fuzzy
        comp.lower_strict = edtf.lower_strict
        comp.upper_strict = edtf.upper_strict
        comp.nat_lang_year = edtf.nat_lang_year
        comp.save_revision().publish()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20201230_1944'),
    ]

    operations = [
        migrations.RunPython(copy_edtf)
    ]
