name: Fernande Breilh Decruck
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      db_service:
        image: postgres
        env:
          POSTGRES_USER: nick
          POSTGRES_DB: decruck
          POSTGRES_PASSWORD: decruck
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install poppler
        run: sudo apt-get install poppler-utils
      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel
      - id: cache-pipenv
        uses: actions/cache@v1
        with:
          path: /home/runner/work/decruck-wagtail/decruck-wagtail/.venv
          key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}
      - name: Run tests
        run: make test
